const esc=value=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]));

export function initTeamChat({supabase,getUser}){
 const button=document.getElementById("teamChatButton"),panel=document.getElementById("teamChatPanel"),messages=document.getElementById("teamChatMessages"),typing=document.getElementById("teamChatTyping"),form=document.getElementById("teamChatForm"),input=document.getElementById("teamChatInput");
 let user=null,profile=null,channel=null,typingTimer=null,typingHeartbeat=null,typingStateTimer=null,syncTimer=null,startPromise=null,lastTyping=false,lastReadAt=null;
 const messageIds=new Set(),remoteTypers=new Map(),databaseTypers=new Map();
 const avatar=person=>person?.avatar_url?`<img src="${esc(person.avatar_url)}" alt="">`:`<span>${esc((person?.display_name||"U").charAt(0).toUpperCase())}</span>`;
 const time=value=>new Date(value).toLocaleTimeString("es",{hour:"2-digit",minute:"2-digit"});
 const scrollBottom=()=>requestAnimationFrame(()=>messages.scrollTop=messages.scrollHeight);
 const messageHTML=item=>{const own=item.user_id===user?.id,author=item.author||profile||{};return`<article class="team-chat-message ${own?"own":"other"}" data-chat-message="${item.id}">${own?"":`<i>${avatar(author)}</i>`}<div><header><strong>${esc(own?"Tú":author.display_name||"Usuario")}</strong><time>${time(item.created_at)}</time></header><p>${esc(item.message).replace(/\n/g,"<br>")}</p></div></article>`};
 const append=item=>{if(!item?.id||messageIds.has(String(item.id)))return;messages.querySelector(".team-chat-empty")?.remove();messageIds.add(String(item.id));messages.insertAdjacentHTML("beforeend",messageHTML(item));scrollBottom()};
 const loadMessages=async({reset=true,showUnread=false}={})=>{const {data,error}=await supabase.from("chat_messages").select("id,user_id,message,created_at,author:profiles!chat_messages_user_id_fkey(id,display_name,avatar_url)").order("created_at",{ascending:true}).limit(200);if(error){if(reset)messages.innerHTML='<p class="team-chat-empty">No se pudo conectar con el chat.</p>';return}if(reset){messages.innerHTML="";messageIds.clear()}let dividerAdded=false;(data||[]).forEach(item=>{if(showUnread&&!dividerAdded&&item.user_id!==user.id&&lastReadAt&&new Date(item.created_at)>new Date(lastReadAt)){messages.insertAdjacentHTML("beforeend",'<div class="team-chat-unread"><span>No leídos</span></div>');dividerAdded=true}append(item)});if(reset&&!data?.length)messages.innerHTML='<p class="team-chat-empty">Aún no hay mensajes. Inicia la conversación.</p>'};
 const loadReadState=async()=>{const {data}=await supabase.from("chat_reads").select("last_read_at").eq("user_id",user.id).maybeSingle();if(data?.last_read_at){lastReadAt=data.last_read_at;return}lastReadAt=new Date().toISOString();await supabase.from("chat_reads").insert({user_id:user.id,last_read_at:lastReadAt})};
 const refreshUnreadIndicator=async()=>{if(!user||!lastReadAt)return;const {count}=await supabase.from("chat_messages").select("id",{count:"exact",head:true}).neq("user_id",user.id).gt("created_at",lastReadAt);button.classList.toggle("has-unread",Boolean(count))};
 const markRead=async()=>{lastReadAt=new Date().toISOString();button.classList.remove("has-unread");await supabase.from("chat_reads").upsert({user_id:user.id,last_read_at:lastReadAt},{onConflict:"user_id"})};
 const noteIncoming=item=>{if(item.user_id===user?.id)return;if(panel.hidden)button.classList.add("has-unread");else markRead()};
 const renderTyping=()=>{const active=new Map(databaseTypers);remoteTypers.forEach((item,id)=>active.set(id,item.name));if(channel&&user)Object.values(channel.presenceState()).flat().forEach(item=>{if(item.user_id!==user.id&&item.typing)active.set(item.user_id,item.name||"Alguien")});const names=[...new Set(active.values())];typing.textContent=names.length===1?`${names[0]} está escribiendo…`:names.length>1?`${names.slice(0,-1).join(", ")} y ${names.at(-1)} están escribiendo…`:""};
 const loadTypingState=async()=>{if(!user)return;const since=new Date(Date.now()-11000).toISOString(),{data}=await supabase.from("chat_typing").select("user_id,updated_at,profile:profiles!chat_typing_user_id_fkey(display_name)").eq("is_typing",true).neq("user_id",user.id).gte("updated_at",since);databaseTypers.clear();(data||[]).forEach(item=>databaseTypers.set(item.user_id,item.profile?.display_name||"Alguien"));renderTyping()};
 const receiveTyping=payload=>{const item=payload?.payload;if(!item||item.user_id===user?.id)return;clearTimeout(remoteTypers.get(item.user_id)?.timer);if(!item.typing){remoteTypers.delete(item.user_id);renderTyping();return}const timer=setTimeout(()=>{remoteTypers.delete(item.user_id);renderTyping()},10500);remoteTypers.set(item.user_id,{name:item.name||"Alguien",timer});renderTyping()};
 const sendTyping=async(state,refresh=false)=>{if(!user||(!refresh&&lastTyping===state))return;lastTyping=state;if(state&&!typingHeartbeat)typingHeartbeat=setInterval(()=>sendTyping(true,true),2500);if(!state){clearInterval(typingHeartbeat);typingHeartbeat=null}const payload={user_id:user.id,name:profile?.display_name||user.email?.split("@")[0]||"Usuario",typing:state};supabase.from("chat_typing").upsert({user_id:user.id,is_typing:state,updated_at:new Date().toISOString()},{onConflict:"user_id"}).then(()=>{});if(!channel)return;await channel.send({type:"broadcast",event:"typing",payload});await channel.track({...payload,online_at:new Date().toISOString()})};
 const connect=async()=>{if(channel)return;channel=supabase.channel("team-chat-general",{config:{broadcast:{self:false},presence:{key:user.id}}}).on("broadcast",{event:"new-message"},event=>{append(event.payload);noteIncoming(event.payload)}).on("broadcast",{event:"typing"},receiveTyping).on("presence",{event:"sync"},renderTyping).on("postgres_changes",{event:"INSERT",schema:"public",table:"chat_messages"},async event=>{const item=event.new,{data:author}=await supabase.from("profiles").select("id,display_name,avatar_url").eq("id",item.user_id).maybeSingle(),complete={...item,author};append(complete);noteIncoming(complete)}).subscribe(status=>{if(status==="SUBSCRIBED"){lastTyping=false;channel.track({user_id:user.id,name:profile.display_name,typing:false,online_at:new Date().toISOString()})}if(status==="CHANNEL_ERROR"||status==="TIMED_OUT")console.warn("No se pudo establecer el canal Realtime del chat:",status)});
 };
 const start=()=>startPromise||(startPromise=(async()=>{user=await getUser();if(!user){startPromise=null;return}const {data}=await supabase.from("profiles").select("id,display_name,avatar_url").eq("id",user.id).maybeSingle();profile=data||{id:user.id,display_name:user.email?.split("@")[0]||"Usuario"};await loadReadState();await loadMessages();await refreshUnreadIndicator();await connect()})());
 button?.addEventListener("click",async event=>{event.stopPropagation();await start();if(!user)return;const open=panel.hidden;panel.hidden=!open;document.body.classList.toggle("chat-open",open);document.body.classList.toggle("sidebar-open",open);document.body.classList.remove("notifications-open");const notifications=document.getElementById("notificationsPanel");if(notifications)notifications.hidden=true;if(open){await Promise.all([loadMessages({showUnread:true}),loadTypingState()]);const unreadDivider=messages.querySelector(".team-chat-unread");await markRead();input.focus();if(unreadDivider)requestAnimationFrame(()=>unreadDivider.scrollIntoView({block:"start"}));else scrollBottom();clearInterval(syncTimer);clearInterval(typingStateTimer);syncTimer=setInterval(()=>{if(!panel.hidden)loadMessages({reset:false})},3000);typingStateTimer=setInterval(()=>{if(!panel.hidden)loadTypingState()},1000)}else{clearInterval(syncTimer);clearInterval(typingStateTimer);await sendTyping(false)}});
 panel?.querySelector("[data-close-team-chat]")?.addEventListener("click",async()=>{panel.hidden=true;document.body.classList.remove("chat-open");clearInterval(syncTimer);clearInterval(typingStateTimer);await sendTyping(false)});
 new MutationObserver(()=>{if(panel.hidden){clearTimeout(typingTimer);clearInterval(syncTimer);clearInterval(typingStateTimer);sendTyping(false)}}).observe(panel,{attributes:true,attributeFilter:["hidden"]});
 input?.addEventListener("input",()=>{input.style.height="auto";input.style.height=`${Math.min(110,input.scrollHeight)}px`;const active=Boolean(input.value.trim());sendTyping(active,active);clearTimeout(typingTimer);if(active)typingTimer=setTimeout(()=>sendTyping(false),10000)});
 input?.addEventListener("keydown",event=>{if(event.key==="Enter"&&!event.shiftKey){event.preventDefault();form.requestSubmit()}});
 form?.addEventListener("submit",async event=>{event.preventDefault();const message=input.value.trim();if(!message||!user)return;input.value="";input.style.height="auto";clearTimeout(typingTimer);sendTyping(false);const temporaryId=`pending-${user.id}-${Date.now()}`;append({id:temporaryId,user_id:user.id,message,created_at:new Date().toISOString(),author:profile});const {data,error}=await supabase.from("chat_messages").insert({user_id:user.id,message}).select("id,user_id,message,created_at").single();if(error){messages.querySelector(`[data-chat-message="${temporaryId}"]`)?.remove();messageIds.delete(temporaryId);input.value=message;input.focus();return}const item={...data,author:profile},temporaryMessage=messages.querySelector(`[data-chat-message="${temporaryId}"]`);messageIds.delete(temporaryId);if(messageIds.has(String(item.id)))temporaryMessage?.remove();else if(temporaryMessage){temporaryMessage.dataset.chatMessage=item.id;messageIds.add(String(item.id))}else append(item);channel?.send({type:"broadcast",event:"new-message",payload:item})});
 window.addEventListener("node:profile-ready",()=>start());
 start();
}
