const clone=value=>{try{return structuredClone(value)}catch{return JSON.parse(JSON.stringify(value))}};
const esc=value=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[char]));
const itemLabel=item=>item?.title||item?.name||item?.text||item?.label||item?.message||"Elemento eliminado";
const itemType=(item,path)=>{const key=String(path.at(-1)||"");if(key.includes("column"))return"Columna";if(key.includes("row"))return"Fila";if(key.includes("block"))return"Contenido";if(key.includes("task")||key.includes("todo"))return"Tarea";if(key.includes("Workspace")||key.includes("Pages"))return"Página";if(key.includes("option"))return"Etiqueta";return"Elemento"};
const same=(a,b)=>JSON.stringify(a)===JSON.stringify(b);

export function createTrashManager({getData,onChange,getUserId}){
 let baseline=null;
 const allIds=value=>{const ids=new Set(),visit=node=>{if(!node||typeof node!=="object")return;if(!Array.isArray(node)&&node.id!=null)ids.add(String(node.id));Object.entries(node).forEach(([key,child])=>{if(key!=="trash")visit(child)})};visit(value);return ids};
 const routeChild=(route,item,index)=>[...route,item&&typeof item==="object"&&item.id!=null?{id:String(item.id)}:index];
 const detect=(before,after,route,found,present)=>{if(Array.isArray(before)&&Array.isArray(after)){const objectsWithId=before.some(item=>item&&typeof item==="object"&&item.id!=null);if(objectsWithId){const nextById=new Map(after.filter(item=>item&&typeof item==="object"&&item.id!=null).map(item=>[String(item.id),item]));before.forEach((item,index)=>{const id=item&&typeof item==="object"&&item.id!=null?String(item.id):null;if(id&&!nextById.has(id)){if(!present.has(id))found.push({value:clone(item),container:clone(route),index,type:itemType(item,route),label:itemLabel(item)});return}if(id)detect(item,nextById.get(id),routeChild(route,item,index),found,present)});return}if(after.length<before.length){const remaining=[...after];before.forEach((item,index)=>{const match=remaining.findIndex(value=>same(value,item));if(match>=0)remaining.splice(match,1);else found.push({value:clone(item),container:clone(route),index,type:itemType(item,route),label:itemLabel(item)})})}return}if(!before||!after||typeof before!=="object"||typeof after!=="object")return;Object.keys(before).forEach(key=>{if(key!=="trash"&&key in after)detect(before[key],after[key],[...route,key],found,present)})};
 const resolve=(root,route)=>{let node=root;for(const token of route){if(node==null)return null;if(token&&typeof token==="object"&&token.id!=null){if(!Array.isArray(node))return null;node=node.find(item=>String(item?.id)===token.id)}else node=node[token]}return node};
 const render=()=>{const data=getData(),list=document.getElementById("trashList");if(!list)return;const entries=[...(data.trash||[])].sort((a,b)=>String(b.deletedAt).localeCompare(String(a.deletedAt)));list.innerHTML=entries.length?entries.map(entry=>`<article class="trash-item" data-trash-id="${esc(entry.trashId)}"><span class="trash-item-icon"><img src="img/emptypaper.png" alt=""></span><div><strong>${esc(entry.label)}</strong><small>${esc(entry.type)} · ${new Date(entry.deletedAt).toLocaleString("es")}</small></div><button type="button" data-trash-restore>Restaurar</button><button class="danger" type="button" data-trash-delete>Eliminar definitivamente</button></article>`).join(""):'<div class="trash-empty"><img src="img/empty.gif" alt="Papelera vacía"><strong>La papelera está vacía</strong><p>Los elementos eliminados aparecerán aquí.</p></div>';list.querySelectorAll("[data-trash-id]").forEach(row=>{const entry=entries.find(item=>item.trashId===row.dataset.trashId);row.querySelector("[data-trash-restore]").onclick=()=>{const container=resolve(data,entry.container);if(!Array.isArray(container)){entry.restoreError=true;render();return}const index=Math.max(0,Math.min(Number(entry.index)||0,container.length));container.splice(index,0,clone(entry.value));data.trash=data.trash.filter(item=>item!==entry);baseline=clone(data);onChange();window.dispatchEvent(new CustomEvent("node:trash-restored"));render()};row.querySelector("[data-trash-delete]").onclick=()=>{data.trash=data.trash.filter(item=>item!==entry);baseline=clone(data);onChange();render()}})};
 const open=()=>{const panel=document.getElementById("trashPanel"),overlay=document.getElementById("trashOverlay");if(!panel||!overlay)return;render();overlay.hidden=false;panel.hidden=false;requestAnimationFrame(()=>{overlay.classList.add("active");panel.classList.add("open")})};
 const close=()=>{const panel=document.getElementById("trashPanel"),overlay=document.getElementById("trashOverlay");panel?.classList.remove("open");overlay?.classList.remove("active");setTimeout(()=>{if(panel)panel.hidden=true;if(overlay)overlay.hidden=true},220)};
 document.getElementById("openTrash")?.addEventListener("click",open);document.querySelector("[data-close-trash]")?.addEventListener("click",close);document.getElementById("trashOverlay")?.addEventListener("click",close);
 return{setBaseline(value){baseline=clone(value)},capture(){const data=getData();if(!baseline){baseline=clone(data);return}const found=[];detect(baseline,data,[],found,allIds(data));if(found.length){data.trash=Array.isArray(data.trash)?data.trash:[];found.forEach(entry=>data.trash.push({...entry,trashId:crypto.randomUUID(),deletedAt:new Date().toISOString(),deletedBy:getUserId?.()||null}))}baseline=clone(data)},render};
}
